from .schemas import (
    ConvictionBet,
    CuratedSource,
    Opportunity,
    Paper,
    Post,
    Role,
    Signal,
    Startup,
    Stat,
    Task,
)

CURATED_SNAPSHOT_DATE = "2026-08-18"


def _src(label: str, url: str, published_at: str = "") -> CuratedSource:
    return CuratedSource(label=label, url=url, published_at=published_at)


MARKET_PULSE = (
    "Verified August 18, 2026: physical-AI companies are shifting from isolated demos "
    "toward fleet learning, production tooling, and real deployments. Figure and "
    "Apptronik are operating at BMW and Robot Park, while Applied Intuition, Axelera, "
    "and Cursor are productizing agentic workflows around physical and software systems."
)

SIGNALS: list[Signal] = [
    Signal(
        label="SHIELD",
        delta="Aug 6",
        color="green",
        text="Shield AI's latest newsroom update details the X-BAT thrust-vectoring system, following an August 5 autonomous-swarm exercise update.",
    ),
    Signal(
        label="DANA",
        delta="Jul 21",
        color="cyan",
        text="Applied Intuition launched Dana as an agentic platform for building, testing, deploying, and operating physical-AI systems.",
    ),
    Signal(
        label="AXELERA",
        delta="Jul 15",
        color="amber",
        text="Axelera released Voyager Wingman to build, debug, and optimize edge-AI pipelines through its Voyager toolkit.",
    ),
    Signal(
        label="1X",
        delta="Jul 9",
        color="cyan",
        text="1X published its 25-DoF, force-controlled NEO hand design and says hundreds have already come off its production line.",
    ),
    Signal(
        label="FLEETS",
        delta="Jun 30",
        color="green",
        text="Figure demonstrated Figure 03 sequencing at BMW, while Apptronik announced active Apollo 2 fleets across Robot Park and customer sites.",
    ),
]

STATS: list[Stat] = [
    Stat(label="Signals Tracked", value="5", delta="curated · verified Aug 18", up=None),
    Stat(label="Opportunities", value="8", delta="sourced opportunity map", up=None),
    Stat(label="Startups Flagged", value="12", delta="focused company watchlist", up=None),
    Stat(label="Hiring Signals", value="8", delta="official careers pages", up=None),
    Stat(label="Research Papers", value="7", delta="primary-source reading queue", up=None),
]

OPPORTUNITIES: list[Opportunity] = [
    Opportunity(
        rank="01",
        title="Robot Policy and Fleet-Learning Engineer",
        domain="Physical AI",
        signal="HIGH",
        fit=97,
        why="Build the policy, data, and evaluation loops that let one model improve across robots and real customer deployments.",
        sourced_fact="Skild acquired Zebra Technologies' robotics division in April 2026, and Apptronik says active Apollo 2 fleets now collect data across Robot Park and customer sites.",
        editorial_take="The strongest hiring signal is moving from benchmark-only VLA work toward engineers who can close the loop between fleet data, policy training, and deployment safety.",
        last_verified=CURATED_SNAPSHOT_DATE,
        sources=[
            _src("Skild acquisition", "https://www.skild.ai/blogs", "2026-04-15"),
            _src("Apptronik Robot Park", "https://apptronik.com/news-collection/welcome-to-robot-park-where-apptroniks-apollo-goes-to-work", "2026-06-30"),
        ],
    ),
    Opportunity(
        rank="02",
        title="Agent Runtime, MCP, and Evaluation Engineer",
        domain="Generative AI",
        signal="HIGH",
        fit=94,
        why="Own permissions, tool reliability, long-horizon evaluation, and observability for agents operating inside real engineering systems.",
        sourced_fact="Cursor 3 added a unified agent workspace and a plugin marketplace built around MCPs, skills, and subagents; Composer 2.5 targets longer-running tasks.",
        editorial_take="Thin chat wrappers are commoditized. Reliable execution, evaluation, and governance are the durable infrastructure layer.",
        last_verified=CURATED_SNAPSHOT_DATE,
        sources=[
            _src("Cursor 3", "https://cursor.com/blog/cursor-3", "2026-04-02"),
            _src("Composer 2.5", "https://cursor.com/changelog/composer-2-5", "2026-05-18"),
        ],
    ),
    Opportunity(
        rank="03",
        title="Edge Inference Compiler and NPU Optimization",
        domain="Edge AI",
        signal="HIGH",
        fit=92,
        why="Reduce model-to-device friction across compilation, scheduling, memory movement, profiling, and hardware-aware accuracy checks.",
        sourced_fact="Axelera released Voyager Wingman in July 2026 after raising more than $250M in February; Hailo's 2026 releases continue to expand commercial edge-AI distribution.",
        editorial_take="Hardware value is realized through software. Compiler and runtime engineers remain scarce because they determine whether models actually meet edge latency and power budgets.",
        last_verified=CURATED_SNAPSHOT_DATE,
        sources=[
            _src("Voyager Wingman", "https://axelera.ai/news/axelera-ai-publicly-releases-voyager-wingman-an-ai-assistant-that-speeds-application-development", "2026-07-15"),
            _src("Hailo newsroom", "https://hailo.ai/company-overview/newsroom/news/", "2026-04-01"),
        ],
    ),
    Opportunity(
        rank="04",
        title="Robotics Deployment and Fleet Reliability Engineer",
        domain="Robotics",
        signal="HIGH",
        fit=90,
        why="Turn policies and robot hardware into observable, recoverable systems that can operate across factories and customer sites.",
        sourced_fact="Figure 03 performed a sequencing workflow at BMW Spartanburg on June 30, and Apptronik reported active Apollo 2 fleets at Robot Park and partner locations the same day.",
        editorial_take="Uptime, telemetry, recovery behavior, and plant integration are becoming more valuable than another controlled demo.",
        last_verified=CURATED_SNAPSHOT_DATE,
        sources=[
            _src("Figure 03 at BMW", "https://www.figure.ai/news/f-03-at-bmw", "2026-06-30"),
            _src("Apptronik Robot Park", "https://apptronik.com/news-collection/welcome-to-robot-park-where-apptroniks-apollo-goes-to-work", "2026-06-30"),
        ],
    ),
    Opportunity(
        rank="05",
        title="Simulation, Digital Twins, and Sim-to-Real",
        domain="Physical AI",
        signal="HIGH",
        fit=87,
        why="Connect high-fidelity simulation, evolving site twins, policy evaluation, and hardware validation into one repeatable workflow.",
        sourced_fact="FieldAI described using NVIDIA Omniverse with field-deployed robots to create continuously evolving digital twins of industrial sites.",
        editorial_take="Simulation is most defensible when it shortens a measured deployment loop, not when it exists as an isolated synthetic-data project.",
        last_verified=CURATED_SNAPSHOT_DATE,
        sources=[
            _src("FieldAI and NVIDIA Omniverse", "https://www.fieldai.com/news/fieldai-and-nvidia-omniverse-building-the-next-generation-of-industrial-ai", "2026-03-16"),
            _src("NVIDIA Isaac Lab", "https://developer.nvidia.com/isaac/lab"),
        ],
    ),
    Opportunity(
        rank="06",
        title="Agentic Coding and Long-Horizon Tooling Engineer",
        domain="Generative AI",
        signal="MEDIUM",
        fit=83,
        why="Build agent harnesses, sandboxes, code-search tools, and tests for tasks that span many actions and repositories.",
        sourced_fact="Cursor says Composer 2.5 improves sustained work on long-running tasks, while Cursor 3 supports parallel agents and handoff between local and cloud work.",
        editorial_take="The open problem is dependable completion under changing code and tools, not generating one more plausible patch.",
        last_verified=CURATED_SNAPSHOT_DATE,
        sources=[
            _src("Composer 2.5", "https://cursor.com/changelog/composer-2-5", "2026-05-18"),
            _src("Cursor 3", "https://cursor.com/blog/cursor-3", "2026-04-02"),
        ],
    ),
    Opportunity(
        rank="07",
        title="Embedded Control and Dexterous Robot Hardware",
        domain="Embedded",
        signal="MEDIUM",
        fit=79,
        why="Own force control, embedded sensing, actuator firmware, diagnostics, and manufacturing test for dexterous humanoid systems.",
        sourced_fact="1X's July 2026 NEO hands use 25 force-controlled degrees of freedom, tactile sensing, and in-house firmware; the company reports hundreds produced.",
        editorial_take="Dexterity makes embedded control and manufacturing quality part of the learning system, not a commodity layer below AI.",
        last_verified=CURATED_SNAPSHOT_DATE,
        sources=[
            _src("NEO hands", "https://www.1x.tech/discover/neos-hands", "2026-07-09"),
            _src("Figure hardware careers", "https://www.figure.ai/careers"),
        ],
    ),
    Opportunity(
        rank="08",
        title="On-Device Multimodal Perception",
        domain="Edge AI",
        signal="MEDIUM",
        fit=75,
        why="Deploy perception and world models against real sensor, compute, latency, and safety constraints.",
        sourced_fact="Wayve says its AI Driver runs on onboard compute and embedded sensors, while Hailo continues to expand edge GenAI and vision accelerator distribution.",
        editorial_take="Engineers who can measure model quality together with thermal, memory, and latency budgets will remain more valuable than cloud-only perception specialists.",
        last_verified=CURATED_SNAPSHOT_DATE,
        sources=[
            _src("Wayve Series D", "https://wayve.ai/press/series-d/", "2026-02-25"),
            _src("Hailo newsroom", "https://hailo.ai/company-overview/newsroom/news/", "2026-04-01"),
        ],
    ),
]

STARTUPS: list[Startup] = [
    Startup(
        name="Figure",
        stage="Series C",
        domain="Physical AI",
        signal="Hot",
        note="Figure 03 is performing a sequencing workflow at BMW Spartanburg with Helix 02 whole-body control.",
        website="https://www.figure.ai",
        sourced_fact="Figure published its Figure 03 BMW sequencing demonstration on June 30, 2026; Figure 02 had contributed to production of 30,000 cars in 2025.",
        editorial_take="Figure now has a stronger deployment signal than a pure manufacturing-volume narrative because the latest work combines perception, manipulation, and locomotion on a factory floor.",
        last_verified=CURATED_SNAPSHOT_DATE,
        sources=[_src("Figure 03 at BMW", "https://www.figure.ai/news/f-03-at-bmw", "2026-06-30")],
    ),
    Startup(
        name="Apptronik",
        stage="Series A",
        domain="Physical AI",
        signal="Hot",
        note="Robot Park and Apollo 2 form a real-world data loop spanning Apptronik, Google DeepMind, and customer sites.",
        website="https://apptronik.com",
        sourced_fact="Apptronik announced a nearly 90,000-square-foot Robot Park and active Apollo 2 fleets across its facility and key partner sites on June 30, 2026.",
        editorial_take="The company is making fleet data collection the bridge between humanoid prototypes and a commercial Apollo 3 fleet.",
        last_verified=CURATED_SNAPSHOT_DATE,
        sources=[_src("Apptronik Robot Park", "https://apptronik.com/news-collection/welcome-to-robot-park-where-apptroniks-apollo-goes-to-work", "2026-06-30")],
    ),
    Startup(
        name="Skild AI",
        stage="Series C",
        domain="Physical AI",
        signal="Hot",
        note="Skild is pairing a heavily funded omni-bodied model thesis with warehouse deployment assets from Zebra's robotics division.",
        website="https://www.skild.ai",
        sourced_fact="Skild announced a $1.4B Series C at a valuation above $14B in January and the acquisition of Zebra Technologies' robotics division in April 2026.",
        editorial_take="The acquisition turns a model-platform thesis into a clearer route to robots, customers, and deployment data.",
        last_verified=CURATED_SNAPSHOT_DATE,
        sources=[
            _src("Skild Series C", "https://www.skild.ai/blogs/series-c", "2026-01-14"),
            _src("Skild blog", "https://www.skild.ai/blogs", "2026-04-15"),
        ],
    ),
    Startup(
        name="Axelera AI",
        stage="Growth",
        domain="Edge AI",
        signal="Hot",
        note="Voyager Wingman connects natural-language agents directly to edge-AI pipeline creation, debugging, and optimization.",
        website="https://axelera.ai",
        sourced_fact="Axelera publicly released Voyager Wingman on July 15, 2026 and says its edge platforms are deployed across more than 500 customers.",
        editorial_take="The latest move makes developer experience, not only accelerator performance, a core part of Axelera's competitive position.",
        last_verified=CURATED_SNAPSHOT_DATE,
        sources=[_src("Voyager Wingman", "https://axelera.ai/news/axelera-ai-publicly-releases-voyager-wingman-an-ai-assistant-that-speeds-application-development", "2026-07-15")],
    ),
    Startup(
        name="Hailo",
        stage="Growth",
        domain="Edge AI",
        signal="Watch",
        note="Hailo continues to widen edge-AI distribution through consumer, commercial, Raspberry Pi, and USB accelerator channels.",
        website="https://hailo.ai",
        sourced_fact="Hailo's 2026 newsroom includes an April 1 ASUS UGen300 USB accelerator update and January launches spanning Raspberry Pi and commercial edge systems.",
        editorial_take="Hailo remains a distribution signal for edge inference becoming a mainstream product component rather than specialist robotics hardware.",
        last_verified=CURATED_SNAPSHOT_DATE,
        sources=[_src("Hailo newsroom", "https://hailo.ai/company-overview/newsroom/news/", "2026-04-01")],
    ),
    Startup(
        name="Physical Intelligence",
        stage="Series B",
        domain="Physical AI",
        signal="Watch",
        note="The π*0.6 technical report extends the company's VLA line with reinforcement learning from experience and human feedback.",
        website="https://www.physicalintelligence.company",
        sourced_fact="Physical Intelligence published π*0.6, an adaptation of π0.6 that applies reinforcement learning with human reward feedback and interventions.",
        editorial_take="The report keeps post-training and experience-driven improvement central to the robot-policy roadmap.",
        last_verified=CURATED_SNAPSHOT_DATE,
        sources=[_src("π*0.6 technical report", "https://www.physicalintelligence.company/download/pistar06.pdf")],
    ),
    Startup(
        name="1X",
        stage="Series B",
        domain="Physical AI",
        signal="Hot",
        note="NEO's latest hands combine dexterity, tactile sensing, force control, and a stated high-volume manufacturing path.",
        website="https://www.1x.tech",
        sourced_fact="1X unveiled 25-DoF NEO hands on July 9, 2026 and says hundreds have been built, with capacity to produce 10,000 hands during the year.",
        editorial_take="1X is treating hands as both an actuator interface and a data-collection surface, which directly links hardware quality to model improvement.",
        last_verified=CURATED_SNAPSHOT_DATE,
        sources=[_src("NEO hands", "https://www.1x.tech/discover/neos-hands", "2026-07-09")],
    ),
    Startup(
        name="FieldAI",
        stage="Growth",
        domain="Robotics",
        signal="Watch",
        note="FieldAI is applying foundation models and evolving digital twins to unstructured industrial environments.",
        website="https://www.fieldai.com",
        sourced_fact="FieldAI announced March 2026 work with NVIDIA on industrial AI and a partnership with Boston Dynamics for dynamic construction environments.",
        editorial_take="Its differentiation is the hard deployment regime: changing sites where uncertainty and physics matter more than scripted navigation.",
        last_verified=CURATED_SNAPSHOT_DATE,
        sources=[
            _src("FieldAI and NVIDIA", "https://www.fieldai.com/news/fieldai-and-nvidia-omniverse-building-the-next-generation-of-industrial-ai", "2026-03-16"),
            _src("FieldAI and Boston Dynamics", "https://www.fieldai.com/news/boston-dynamics-and-fieldai-partner-to-bring-robots-into-uncharted-and-dynamic-environments", "2026-03-12"),
        ],
    ),
    Startup(
        name="Applied Intuition",
        stage="Growth",
        domain="Physical AI",
        signal="Hot",
        note="Dana packages agents, data, tooling, evaluation, traceability, and governance for safety-critical physical-AI work.",
        website="https://www.appliedintuition.com",
        sourced_fact="Applied Intuition launched Dana on July 21, 2026 and says internal and select customer use reduced some vehicle-development phases from months to days.",
        editorial_take="Applied is extending its autonomy infrastructure moat into an agentic control plane for physical-AI engineering workflows.",
        last_verified=CURATED_SNAPSHOT_DATE,
        sources=[_src("Dana launch", "https://www.appliedintuition.com/press-releases/applied-intuition-launches-dana", "2026-07-21")],
    ),
    Startup(
        name="Wayve",
        stage="Series D",
        domain="Edge AI",
        signal="Hot",
        note="Wayve is moving end-to-end embodied driving AI into robotaxi trials and automaker deployment channels.",
        website="https://wayve.ai",
        sourced_fact="Wayve raised a $1.2B Series D at an $8.6B post-money valuation in February 2026 and announced a Tokyo robotaxi collaboration in March.",
        editorial_take="Its licensing and onboard-compute model is a capital-efficient test of whether one driving foundation model can generalize across markets and vehicles.",
        last_verified=CURATED_SNAPSHOT_DATE,
        sources=[
            _src("Wayve Series D", "https://wayve.ai/press/series-d/", "2026-02-25"),
            _src("Wayve press room", "https://wayve.ai/press/", "2026-03-12"),
        ],
    ),
    Startup(
        name="Shield AI",
        stage="Growth",
        domain="Physical AI",
        signal="Hot",
        note="Shield AI's August updates span autonomous swarms, maritime teaming, aircraft autonomy, and X-BAT vertical-flight systems.",
        website="https://shield.ai",
        sourced_fact="Shield AI's newsroom lists an August 6 X-BAT engineering update and an August 5 autonomous-swarm exercise with Taiwan's NCSIST.",
        editorial_take="The pace and breadth of field programs make Shield AI a strong signal for production autonomy under contested, multi-asset constraints.",
        last_verified=CURATED_SNAPSHOT_DATE,
        sources=[_src("Shield AI newsroom", "https://shield.ai/newsroom/", "2026-08-06")],
    ),
    Startup(
        name="Cursor",
        stage="Growth",
        domain="Generative AI",
        signal="Hot",
        note="Cursor is expanding from an AI IDE into a workspace for parallel local and cloud agents backed by its own coding models.",
        website="https://cursor.com",
        sourced_fact="Cursor launched Cursor 3 on April 2 and Composer 2.5 on May 18, 2026, emphasizing parallel agents and sustained long-horizon work.",
        editorial_take="Cursor's moat is increasingly the integrated model, runtime, evaluation, and collaboration surface rather than code completion alone.",
        last_verified=CURATED_SNAPSHOT_DATE,
        sources=[
            _src("Cursor 3", "https://cursor.com/blog/cursor-3", "2026-04-02"),
            _src("Composer 2.5", "https://cursor.com/changelog/composer-2-5", "2026-05-18"),
        ],
    ),
]

ROLES: list[Role] = [
    Role(
        company="Figure",
        role="Helix AI Engineer, Robot Learning",
        type="San Jose · Full-time",
        signal="OPEN · verified Aug 18",
        color="cyan",
        url="https://www.figure.ai/careers",
        tags=["robotics", "physical-ai"],
        last_verified=CURATED_SNAPSHOT_DATE,
        sources=[_src("Figure careers", "https://www.figure.ai/careers")],
    ),
    Role(
        company="Cursor",
        role="Software Engineer, Agent Evaluation and Quality",
        type="San Francisco / New York · Full-time",
        signal="OPEN · verified Aug 18",
        color="green",
        url="https://cursor.com/careers",
        tags=["llm", "agentic"],
        last_verified=CURATED_SNAPSHOT_DATE,
        sources=[_src("Cursor careers", "https://cursor.com/careers")],
    ),
    Role(
        company="1X",
        role="Embedded Firmware Engineer, NEO",
        type="San Carlos · Full-time",
        signal="OPEN · verified Aug 18",
        color="amber",
        url="https://www.1x.tech/careers",
        tags=["robotics", "embedded"],
        last_verified=CURATED_SNAPSHOT_DATE,
        sources=[_src("1X careers", "https://www.1x.tech/careers")],
    ),
    Role(
        company="Applied Intuition",
        role="Software Engineer, Physical AI",
        type="Ann Arbor · Full-time",
        signal="OPEN · verified Aug 18",
        color="cyan",
        url="https://www.appliedintuition.com/careers",
        tags=["robotics", "physical-ai"],
        last_verified=CURATED_SNAPSHOT_DATE,
        sources=[_src("Applied Intuition careers", "https://www.appliedintuition.com/careers")],
    ),
    Role(
        company="Apptronik",
        role="Robotics and AI openings",
        type="Austin · See current listings",
        signal="CAREERS PAGE ACTIVE",
        color="cyan",
        url="https://apptronik.com/careers/job-listings",
        tags=["robotics", "physical-ai"],
        last_verified=CURATED_SNAPSHOT_DATE,
        sources=[_src("Apptronik job listings", "https://apptronik.com/careers/job-listings")],
    ),
    Role(
        company="Skild AI",
        role="Robotics research and engineering openings",
        type="See current listings",
        signal="CAREERS PAGE ACTIVE",
        color="cyan",
        url="https://www.skild.ai/career",
        tags=["robotics", "physical-ai"],
        last_verified=CURATED_SNAPSHOT_DATE,
        sources=[_src("Skild AI careers", "https://www.skild.ai/career")],
    ),
    Role(
        company="Shield AI",
        role="Autonomy and robotics openings",
        type="Multiple locations",
        signal="CAREERS PAGE ACTIVE",
        color="green",
        url="https://shield.ai/careers/",
        tags=["robotics", "physical-ai"],
        last_verified=CURATED_SNAPSHOT_DATE,
        sources=[_src("Shield AI careers", "https://shield.ai/careers/")],
    ),
    Role(
        company="Wayve",
        role="Embodied AI and autonomy openings",
        type="London / Sunnyvale · See listings",
        signal="CAREERS PAGE ACTIVE",
        color="green",
        url="https://wayve.ai/careers/",
        tags=["edge-ai", "physical-ai"],
        last_verified=CURATED_SNAPSHOT_DATE,
        sources=[_src("Wayve careers", "https://wayve.ai/careers/")],
    ),
]

PAPERS: list[Paper] = [
    Paper(
        title="Foundation Models in Robotics: A Comprehensive Review of Methods, Models, Datasets, Challenges and Future Research Directions",
        venue="arXiv 2026",
        tags=["Robotics", "Foundation Models"],
        read=False,
        url="https://arxiv.org/abs/2604.15395",
        last_verified=CURATED_SNAPSHOT_DATE,
        sources=[_src("Paper", "https://arxiv.org/abs/2604.15395", "2026-04")],
    ),
    Paper(
        title="π*0.6: a VLA That Learns From Experience",
        venue="Physical Intelligence technical report",
        tags=["Physical AI", "VLA", "RL"],
        read=False,
        url="https://www.physicalintelligence.company/download/pistar06.pdf",
        last_verified=CURATED_SNAPSHOT_DATE,
        sources=[_src("Technical report", "https://www.physicalintelligence.company/download/pistar06.pdf")],
    ),
    Paper(
        title="π0.5: a Vision-Language-Action Model with Open-World Generalization",
        venue="arXiv 2025",
        tags=["Physical AI", "VLA", "Policy"],
        read=False,
        url="https://arxiv.org/abs/2504.16054",
        last_verified=CURATED_SNAPSHOT_DATE,
        sources=[_src("Paper", "https://arxiv.org/abs/2504.16054", "2025-04-22")],
    ),
    Paper(
        title="π0: A Vision-Language-Action Flow Model for General Robot Control",
        venue="arXiv 2024",
        tags=["Physical AI", "VLA", "Policy"],
        read=False,
        url="https://arxiv.org/abs/2410.24164",
        last_verified=CURATED_SNAPSHOT_DATE,
        sources=[_src("Paper", "https://arxiv.org/abs/2410.24164", "2024-10")],
    ),
    Paper(
        title="Genesis: A Generative and Universal Physics Engine for Robotics",
        venue="arXiv 2024",
        tags=["Robotics", "Simulation"],
        read=False,
        url="https://arxiv.org/abs/2412.04325",
        last_verified=CURATED_SNAPSHOT_DATE,
        sources=[_src("Paper", "https://arxiv.org/abs/2412.04325", "2024-12")],
    ),
    Paper(
        title="Humanoid World Models: Open World Foundation Models for Humanoid Robotics",
        venue="arXiv 2025",
        tags=["Physical AI", "World Models"],
        read=False,
        url="https://arxiv.org/abs/2506.01182",
        last_verified=CURATED_SNAPSHOT_DATE,
        sources=[_src("Paper", "https://arxiv.org/abs/2506.01182", "2025-06")],
    ),
    Paper(
        title="Channel-Adaptive Edge AI: Maximizing Inference Throughput by Adapting Computational Complexity to Channel States",
        venue="arXiv 2026",
        tags=["Edge AI", "Inference"],
        read=False,
        url="https://arxiv.org/abs/2603.03146",
        last_verified=CURATED_SNAPSHOT_DATE,
        sources=[_src("Paper", "https://arxiv.org/abs/2603.03146", "2026-03")],
    ),
]

POSTS: list[Post] = [
    Post(
        angle="Take",
        text="Physical AI's moat is moving from demo quality to learning-loop quality. Figure at BMW and Apptronik's Robot Park both point to the same constraint: fleet data, recovery, and uptime now matter as much as the policy.",
        tags=["PhysicalAI", "Robotics"],
        source_ref="Figure and Apptronik · Jun 30, 2026",
    ),
    Post(
        angle="Thread",
        text="Five production signals worth watching: Figure at BMW, Apollo 2 fleets, 1X's 25-DoF hands, Applied's Dana platform, and Axelera's Wingman. The common layer is tooling that closes the gap between model and deployed machine.",
        tags=["Robotics", "EdgeAI"],
        source_ref="Primary company updates · verified Aug 18, 2026",
    ),
    Post(
        angle="Contrarian",
        text="The next robotics bottleneck may not be a larger VLA. It may be the unglamorous stack around it: embedded sensing, observability, fleet recovery, evaluation, and the data contracts that let failures improve the next policy.",
        tags=["Robotics", "Systems"],
        source_ref="Figure · Apptronik · 1X deployment signals",
    ),
]

TASKS: list[Task] = [
    Task(
        id=1,
        priority="P0",
        task="Tailor two applications to verified Figure, 1X, Applied, or Cursor openings",
        domain="Job Applications",
        time="1.5h",
        description="Use the official careers links in Career Radar. Reference one current product milestone and one directly relevant system you have shipped; do not send a generic robotics or AI resume.",
    ),
    Task(
        id=2,
        priority="P0",
        task="Add failure recovery and per-source health to one portfolio service",
        domain="Production Engineering",
        time="2h",
        description="Implement last-known-good state, last attempt, last success, a sanitized error code, and one integration test. Publish the operational tradeoff in the README.",
    ),
    Task(
        id=3,
        priority="P1",
        task="Prototype an edge-AI pipeline and capture latency, memory, and accuracy",
        domain="Edge AI",
        time="3h",
        description="Use ONNX Runtime, TensorRT, or available edge hardware. Compare at least two precisions and record p50/p95 latency plus memory, not only throughput.",
    ),
    Task(
        id=4,
        priority="P1",
        task="Build a ROS2 deployment drill with telemetry and restart behavior",
        domain="Robotics",
        time="2h",
        description="Run a Nav2 or manipulation flow, inject one node failure, and demonstrate detection, degraded behavior, and recovery in a short recording.",
    ),
    Task(
        id=5,
        priority="P1",
        task="Read π*0.6 and extract one post-training experiment",
        domain="Physical AI",
        time="1.5h",
        description="Focus on the RL recipe, feedback source, and evaluation. Write one experiment you could reproduce with a smaller policy or simulated task.",
    ),
    Task(
        id=6,
        priority="P1",
        task="Create a long-horizon agent evaluation with a deterministic verifier",
        domain="Generative AI",
        time="2h",
        description="Define one repository task, its allowed tools, a test-based verifier, timeout behavior, and a trace. Run it multiple times and report completion variance.",
    ),
    Task(
        id=7,
        priority="P2",
        task="Publish one sourced systems take from the August 18 watchlist",
        domain="Build in Public",
        time="45m",
        description="Use a primary-source link, clearly separate the sourced fact from your interpretation, and avoid unsupported market-size or hiring claims.",
    ),
]

WEEKLY_WINS = [
    "Replaced inflated demo totals with exact counts from the maintained fallback collections.",
    "Refocused the startup radar on 12 companies with first-party provenance and an August 18 verification date.",
    "Added production reliability gates across authorization, source health, browser flows, and content freshness.",
]

WEEKLY_GAPS = [
    "Production smoke checks require repository variables for the deployed frontend and API URLs before the scheduled workflow can run.",
    "Curated facts still require a human source review; the weekly workflow detects age and synchronization drift but does not invent updates.",
    "Live job-board ingestion remains inherently noisy, so Career Radar keeps a small verified fallback when provider data is cold.",
]

CONVICTION_BETS: list[ConvictionBet] = [
    ConvictionBet(label="Fleet reliability for physical AI", conviction=94),
    ConvictionBet(label="Edge compiler and runtime tooling", conviction=89),
    ConvictionBet(label="Deterministic evaluation for agents", conviction=86),
]

NEXT_WEEK_FOCUS = (
    "Configure deployed smoke-test URLs, review the first scheduled freshness report, and use source-health telemetry to tune ingestion providers without hiding failures."
)
