from __future__ import annotations

import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
BACKEND_ROOT = ROOT / "backend"
FRONTEND_FILE = ROOT / "frontend" / "src" / "lib" / "mock-data.ts"

sys.path.insert(0, str(BACKEND_ROOT))

from app import mock_data  # noqa: E402


def dump_models(items):
    return [item.model_dump() if hasattr(item, "model_dump") else item for item in items]


def to_ts(name: str, value, ts_type: str | None = None) -> str:
    type_part = f": {ts_type}" if ts_type else ""
    return f"export const {name}{type_part} = {json.dumps(value, indent=2, ensure_ascii=False)};\n"


content = f"""import type {{
  Signal, Stat, Opportunity, Startup, Role,
  Paper, Post, Task, ConvictionBet,
}} from "./types";

// Generated by scripts/sync_mock_data.py from backend/app/mock_data.py.
// Edit the backend source of truth, then rerun:
//   backend/.venv/bin/python scripts/sync_mock_data.py

{to_ts("signals", dump_models(mock_data.SIGNALS), "Signal[]").rstrip()}

{to_ts("marketPulse", mock_data.MARKET_PULSE).rstrip()}

{to_ts("stats", dump_models(mock_data.STATS), "Stat[]").rstrip()}

{to_ts("opportunities", dump_models(mock_data.OPPORTUNITIES), "Opportunity[]").rstrip()}

{to_ts("startups", dump_models(mock_data.STARTUPS), "Startup[]").rstrip()}

{to_ts("roles", dump_models(mock_data.ROLES), "Role[]").rstrip()}

{to_ts("papers", dump_models(mock_data.PAPERS), "Paper[]").rstrip()}

{to_ts("posts", dump_models(mock_data.POSTS), "Post[]").rstrip()}

{to_ts("tasks", dump_models(mock_data.TASKS), "Task[]").rstrip()}

{to_ts("weeklyWins", mock_data.WEEKLY_WINS).rstrip()}

{to_ts("weeklyGaps", mock_data.WEEKLY_GAPS).rstrip()}

{to_ts("convictionBets", dump_models(mock_data.CONVICTION_BETS), "ConvictionBet[]").rstrip()}

{to_ts("nextWeekFocus", mock_data.NEXT_WEEK_FOCUS).rstrip()}
"""

FRONTEND_FILE.write_text(content + "\n", encoding="utf-8")
print(f"Wrote {FRONTEND_FILE}")
